// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2jZjk85MvL5HjKDghVSjwAVtiNWj3Pc',
    appId: '1:603989535576:web:21546f404e6a0e42fe932d',
    messagingSenderId: '603989535576',
    projectId: 'student-registration-app-new',
    authDomain: 'student-registration-app-new.firebaseapp.com',
    storageBucket: 'student-registration-app-new.firebasestorage.app',
    measurementId: 'G-H5CF28Q2H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHblLZGSpSGsqIf3I98MeqNOHnlxdxNLA',
    appId: '1:603989535576:android:8f757999e2ab46f8fe932d',
    messagingSenderId: '603989535576',
    projectId: 'student-registration-app-new',
    storageBucket: 'student-registration-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_OQA1QRPWawGZ7TvleSkIP7B2mhu9i4',
    appId: '1:603989535576:ios:27867a91edae4344fe932d',
    messagingSenderId: '603989535576',
    projectId: 'student-registration-app-new',
    storageBucket: 'student-registration-app-new.firebasestorage.app',
    iosBundleId: 'com.blueray.SteudentRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_OQA1QRPWawGZ7TvleSkIP7B2mhu9i4',
    appId: '1:603989535576:ios:cd63eed5b1a7adbbfe932d',
    messagingSenderId: '603989535576',
    projectId: 'student-registration-app-new',
    storageBucket: 'student-registration-app-new.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT2jZjk85MvL5HjKDghVSjwAVtiNWj3Pc',
    appId: '1:603989535576:web:9e21efd98e7f8f2ffe932d',
    messagingSenderId: '603989535576',
    projectId: 'student-registration-app-new',
    authDomain: 'student-registration-app-new.firebaseapp.com',
    storageBucket: 'student-registration-app-new.firebasestorage.app',
    measurementId: 'G-J2RN5RYN6R',
  );
}
